services:
  flask-app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/myapp
    volumes:
      - .:/app
    command: sh -c "sleep 5 && python3 app.py"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: